<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="5.41.0" />
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crud.AssetManagement.Infrastructure\Crud.AssetManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
