<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="5.41.0" />
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crud.AssetManagement.DTOs\Crud.AssetManagement.DTOs.csproj" />
    <ProjectReference Include="..\Crud.AssetManagement.Infrastructure\Crud.AssetManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
