<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="5.41.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crud.AssetManagement.Queries\Crud.AssetManagement.Queries.csproj" />
    <ProjectReference Include="..\Crud.AssetManagement.DTOs\Crud.AssetManagement.DTOs.csproj" />
  </ItemGroup>

</Project>
